### PR TITLE
GitHub Actions configuration

### PR DESCRIPTION
**Pull request by ColemanKobe**
# PyYAML

## Description

The PyYAML dependency is added to the lock and toml files pertaining to Poetry in order to create configuration files. This is something intended for contributors in multiple feature branches to use. Further documentation is available in [this link](https://pyyaml.org/wiki/PyYAMLDocumentation).

Update: This version has boolean conversion when parsing YAML files. Switched dependencies so that it has a newer version that drops this boolean conversion automatically, linked [here](https://pypi.org/project/ruamel.yaml/)

Meant to address issue #4

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @ColemanKobe 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Comment by mariakimheinert** [comment]
Hi @ColemanKobe,

For feature pull requests, please request reviews from team members instead of Saejin or me.

We will review the release candidate for each sprint but will leave reviewing feature PRs for teams to do by themselves 🙂 

Please let me know if you have any questions about the feature PR review process!

**Comment by ColemanKobe** [comment]
That's right. My apologies for that

**Comment by mariakimheinert** [comment]
No worries, @ColemanKobe. This is something I will clarify for everyone since I don't believe I've explicitly mentioned it before.

**Review by favourojo — DISMISSED** [review]
Looks great!

**Review by ullrichd21 — APPROVED** [review]
This is some super duper work my man!

**Review by favourojo — APPROVED** [review]
Looks good!

**Pull request merged**
