### PR TITLE
Feature gui

### PR DESCRIPTION
**Pull request by ullrichd21**
# Feature GUI

## Description

To run just create a GUI object. Call `get_data()` after the GUI has closed to get the config data.

EX:
```Python
gui = Gui()
data = gui.get_data() # <---- This line does not run until the GUI closes.
# Do stuff with the data here.
```

Test cases implemented (though they could be improved with the addition of pytest-qt).

There are a few outstanding features left to add, such as some missing options however it should be almost all there.

Also doesn't have version lists for `gatorgrader` and `gatorgradle` from GitHub yet but that will be added with a separate feature.

**Note about linting:**
This will _not_ pass lint until .pylintrc is added to the repo/github actions as it whitelists the PyQt5 module. Pylint throws a fit because it doesn't check c++ packages by default.

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @ullrichd21 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by ColemanKobe — APPROVED** [review]
Looks good to me!

**Review by ColemanKobe — APPROVED** [review]
Looks great! Nice testing

**Review by favourojo — APPROVED** [review]
The file looks ready to go!

**Review by WesleyL30 — COMMENTED** [review]
Looks good!

**Pull request merged**
