### PR TITLE
Cli

### PR DESCRIPTION
**Pull request by WesleyL30**
# Command Line Interface Input

## Description
This pull request implements the command line functionality for GatorConfigthrough the use of Typer.

### Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @WesleyL30 
- @favourojo 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by PaigeCD — APPROVED** [review]
I think this looks good. Be sure to resolve the conflicting files.

**Review by ullrichd21 — APPROVED** [review]
Resolve the conflicts and it looks good 👍🏻

**Review by ullrichd21 — APPROVED** [review]
Looks superb

**Review by PaigeCD — APPROVED** [review]
Looks good.

**Pull request merged**
