### PR TITLE
Feature/logo

### PR DESCRIPTION
**Pull request by ullrichd21**
# LOGO

## Description

#51
I make the logo...

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @ullrichd21 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by WesleyL30 — APPROVED** [review]
Impressive artistic skills!

**Review by favourojo — APPROVED** [review]
Logo looks good!

**Review by ColemanKobe — APPROVED** [review]
Just amazing. Perfect.

**Review by PaigeCD — APPROVED** [review]
It's fine.

**Pull request merged**
