### PR TITLE
Feature/default checks

### PR DESCRIPTION
**Pull request by ColemanKobe**
# Default Checks

## Description

This PR is meant to address issue #12

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @ColemanKobe 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by WesleyL30 — CHANGES_REQUESTED** [review]
Looks good, but the user should be prompted about which checks are there by default so they don't add another "--exists"

**Comment by Michionlion** [comment]
Quick reminder: checks have a different syntax now than in the example configuration from the GatorGradle README. Check the newer [simple-assignment](https://github.com/GatorEducator/simple-assignment) sample.

**Comment by ColemanKobe** [comment]
Hi @Michionlion. Do you happen to have a list of the checks that your action supports, such as `ConfirmFileExists`?

**Comment by Michionlion** [comment]
@ColemanKobe gatorgradle-action supports every check GatorGrader supports (it passed them right through to GatorGradle, which passes them through to GatorGrader); so, the full list is available on [gatorgrader.org](https://www.gatorgrader.org/ember) or by running `gatorgrader.py ListChecks` in a clone of the GatorGrader repository.

**Review by WesleyL30 — APPROVED** [review]
Looks good!

**Pull request merged**
